pipeline {
    agent {
        kubernetes {
            label 'notes-pod'
            defaultContainer 'kubectl'
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - cat
    tty: true
"""
        }
    }

    stages {
        stage('Deploy Notes API') {
            steps {
                container('kubectl') {
                    // Aplicar los manifests de Kubernetes
                    sh 'kubectl apply -f ./k8s/deployment.yaml'
                    sh 'kubectl apply -f ./k8s/service.yaml'
                    
                    // Optional: chequear que los pods estén running
                    sh 'kubectl get pods -n default'
                }
            }
        }
    }
}
